Messages et noms de fonctions plus clairs

diff --git a/src/trishell b/src/trishell
--- a/src/trishell
+++ b/src/trishell
@@ -56,7 +56,7 @@ firstIFS=$IFS
 IFS=\ 
 if [ $# -gt 4 ]
 then
-    echo "Trop d'arguments"
+    echo "Il y a trop d'argument, usage: $0 [-R] [-nsmleptg] dir"
     IFS=$firstIFS
     exit 1
 fi
@@ -73,26 +73,26 @@ for i in $*
 do
     if [ $i = "-R" ]
     then
-        test $display = true && echo "Doublon dans les parametres" && exit 2 
+        test $display = true && echo "Le drapeau -R est en doublon dans les paramètres" && exit 2 
         display=true
     elif [ $i = "-d" ]
     then
-        test $asc = false && echo "Doublon dans les parametres" && exit 2 
+        test $asc = false && echo "Le drapeau -d est en doublon dans les paramètres" && exit 2 
         asc=false
     elif [[ $i =~ ^[^-] ]]
     then
-        test $path != NULL && echo "Doublon dans les parametres" && exit 2 
-        ! test -d "$i" && echo "Chemin incorrect" && exit 4
+        test $path != NULL && echo "Doublon dans les chemins spécifiés" && exit 2 
+        ! test -d "$i" && echo "Le chemin spécifié incorrect" && exit 4
         path=$i
     else
-        test $sortOrder != NULL && echo "Doublon dans les parametres" && exit 2 
+        test $sortOrder != NULL && echo "Doublon dans les paramètres de tri" && exit 2 
         sortOrder=$i
         #On récup la longueur de la chaine, pour avoir le nombre de sort
         sortLength=${#sortOrder}
     fi
 done
 
-test $path = NULL && echo "Veuillez indiquer  un chemin" && exit 3
+test $path = NULL && echo "Veuillez indiquer un chemin correct, usage: $0 [-R] [-nsmleptg] dir" && exit 3
 
 #START OF PROG
 
@@ -116,7 +116,7 @@ allData=${allData%?}
 #Tout le temps le meme principe
 #Renvoie 1 si $1 < $2, 0 si $1 > $2, 2 si $1=$2
 
-nameComp(){
+nameSort(){
     if test $1 \< $2 
     then
         echo 1
@@ -128,7 +128,7 @@ nameComp(){
     fi
 }
 
-sizeComp(){
+sizeSort(){
     # Considère toujours les dossiers comme plus petit que les fichiers
     if test -d $1
     then
@@ -151,7 +151,7 @@ sizeComp(){
     fi
 }
 
-lastModifComp(){
+lastChangeSort(){
     local timestamp1=`stat -c '%y' $1`
     local timestamp2=`stat -c '%y' $2`
     if test $timestamp1 \< $timestamp2
@@ -165,7 +165,7 @@ lastModifComp(){
     fi
 }
 
-nbLinesComp(){
+linesSort(){
      # Considère toujours les dossiers comme plus petit que les fichiers
     if test -d $1
     then
@@ -188,7 +188,7 @@ nbLinesComp(){
     fi
 }
 
-extensionComp(){
+extensionSort(){
     #chaine 1 et 2 sont les extensions
     # awk -F. separate the string by dot
     # print $NF will print the last one   
@@ -206,7 +206,7 @@ extensionComp(){
     fi
 }
 
-typeComp(){
+typeSort(){
     # Répertoire: valeur 1
     # Fichier: valeur 2
     # Lien symbolique: valeur 3
@@ -266,7 +266,7 @@ typeComp(){
     fi
 }
 
-propComp(){
+ownerSort(){
     # $1 $2 est le chemin de ce fichier ou répertoire
     # compare the owner name of 2 files or folders.
     # f5 user
@@ -286,7 +286,7 @@ propComp(){
     fi
 }
 
-groupComp(){
+groupSort(){
     # $1 $2 est le chemin de ce fichier ou répertoire
     # compare the group name of 2 files or folders.
     # f5 user
@@ -306,7 +306,7 @@ groupComp(){
 }
 
 #Fonction de base pour comparer
-doHeIsLower(){
+getLowest(){
     if [ $sortOrder = NULL ]
     then
         echo 1
@@ -319,15 +319,15 @@ doHeIsLower(){
         local res
         #On compare
         case $char in
-        n) res=`nameComp $1 $2`;;
-        s) res=`sizeComp $1 $2`;;
-        m) res=`lastModifComp $1 $2`;;
-        l) res=`nbLinesComp $1 $2`;;
-        e) res=`extensionComp $1 $2`;;
-        t) res=`typeComp $1 $2`;;
-        p) res=`propComp $1 $2`;;
-        g) res=`groupComp $1 $2`;;
-        *) echo "Parametre de tri pas bon " && exit 10;;
+        n) res=`nameSort $1 $2`;;
+        s) res=`sizeSort $1 $2`;;
+        m) res=`lastChangeSort $1 $2`;;
+        l) res=`linesSort $1 $2`;;
+        e) res=`extensionSort $1 $2`;;
+        t) res=`typeSort $1 $2`;;
+        p) res=`ownerSort $1 $2`;;
+        g) res=`groupSort $1 $2`;;
+        *) echo "Le paramètre de tri spécifié est invalide" && exit 10;;
         esac
 
         #Si l'ordre décroissant est actif, alors on inverse 1 et 0
@@ -346,7 +346,7 @@ doHeIsLower(){
         if [ $res -eq 2 ]
         then
             local tmp=`expr $3 + 1`
-            echo `doHeIsLower "$i" "$res" $tmp`
+            echo `getLowest "$i" "$res" $tmp`
         else
         #Sinon on affiche le resultat
             echo "$res"
@@ -358,7 +358,7 @@ getLast(){
     local res=`echo $1 | cut -d' ' -f1`
     for i in $1
     do
-        if [ `doHeIsLower "$i" "$res" 0` = 1 ]
+        if [ `getLowest "$i" "$res" 0` = 1 ]
         then
             res=$i
         fi
