Fix read args

diff --git a/src/trishell b/src/trishell
--- a/src/trishell
+++ b/src/trishell
@@ -53,11 +53,10 @@ case "$1" in
 esac
 
 firstIFS=$IFS
-IFS=\ 
+IFS=$' \t\n'
 if [ $# -gt 4 ]
 then
     echo "Trop d'arguments"
-    IFS="$firstIFS"
     exit 1
 fi
 
@@ -87,8 +86,15 @@ do
     else
         test $sortOrder != NULL && echo "Doublon dans les parametres" && exit 2 
         sortOrder="$i"
-        #On récup la longueur de la chaine, pour avoir le nombre de sort
         sortLength=${#sortOrder}
+
+        for a in $(seq 3 $(($sortLength+1)))
+        do
+            if ! [[ $(echo '\'$sortOrder | cut -c$a) =~ [n|s|m||l|e|t|p|g] ]] 
+            then
+                echo "Parametre de tri invalide " && exit 2
+            fi
+        done
     fi
 done
 
@@ -98,7 +104,6 @@ if [ $sortOrder = NULL ]
 then
     sortOrder="-n"
 fi
-
 #START OF PROG
 firstPath=`pwd`
 cd "$path"
@@ -121,10 +126,10 @@ done
 #Renvoie 1 si $1 < $2, 0 si $1 > $2, 2 si $1=$2
 
 nameSort(){
-    if test $1 \< $2 
+    if test "$1" \< "$2" 
     then
         echo 1
-    elif test $1 = $2
+    elif test "$1" = "$2"
     then
         echo 2
     else
@@ -134,19 +139,19 @@ nameSort(){
 
 sizeSort(){
     # Considère toujours les dossiers comme plus petit que les fichiers
-    if test -d $1
+    if test -d "$1"
     then
         echo 1
-    elif test -d $2
+    elif test -d "$2"
     then
         echo 0
     else
-        local res1=`wc -c $1 | cut -d' ' -f1`
-        local res2=`wc -c $2 | cut -d' ' -f1`
-        if [ $res1 -lt $res2 ]
+        local res1=`wc -c "$1" | cut -d' ' -f1`
+        local res2=`wc -c "$2" | cut -d' ' -f1`
+        if [[ $res1 -lt $res2 ]]
         then
             echo 1
-        elif [ $res1 -eq $res2 ]
+        elif [[ $res1 -eq $res2 ]]
         then
             echo 2
         else
@@ -156,8 +161,8 @@ sizeSort(){
 }
 
 lastChangeSort(){
-    local timestamp1=`stat -c '%y' $1`
-    local timestamp2=`stat -c '%y' $2`
+    local timestamp1=`stat -c '%y' "$1"`
+    local timestamp2=`stat -c '%y' "$2"`
     if test $timestamp1 \< $timestamp2
     then
         echo 1
@@ -171,15 +176,15 @@ lastChangeSort(){
 
 linesSort(){
      # Considère toujours les dossiers comme plus petit que les fichiers
-    if test -d $1
+    if test -d "$1"
     then
         echo 1
-    elif test -d $2
+    elif test -d "$2"
     then
         echo 0
     else
-        local res1=`wc -l $1 | cut -d' ' -f1`
-        local res2=`wc -l $2 | cut -d' ' -f1`
+        local res1=`wc -l "$1" | cut -d' ' -f1`
+        local res2=`wc -l "$2" | cut -d' ' -f1`
         if [ $res1 -lt $res2 ]
         then
             echo 1
@@ -313,21 +318,21 @@ groupSort(){
 getLowest(){
     if [ $3 -ge $sortLength ]
     then
-        echo 1
+        echo "1"
     else
         #On recupere le nom de la fonction de tri aproprié
         local char=`echo '\'$sortOrder | cut -c$(($3+3))`
         local res
         #On compare
         case $char in
-        n) res=`nameSort $1 $2`;;
-        s) res=`sizeSort $1 $2`;;
-        m) res=`lastChangeSort $1 $2`;;
-        l) res=`linesSort $1 $2`;;
-        e) res=`extensionSort $1 $2`;;
-        t) res=`typeSort $1 $2`;;
-        p) res=`ownerSort $1 $2`;;
-        g) res=`groupSort $1 $2`;;
+        n) res=`nameSort "$1" "$2"`;;
+        s) res=`sizeSort "$1" "$2"`;;
+        m) res=`lastChangeSort "$1" "$2"`;;
+        l) res=`linesSort "$1" "$2"`;;
+        e) res=`extensionSort "$1" "$2"`;;
+        t) res=`typeSort "$1" "$2"`;;
+        p) res=`ownerSort "$1" "$2"`;;
+        g) res=`groupSort "$1" "$2"`;;
         *) echo "Le paramètre de tri spécifié est invalide" && exit 10;;
         esac
         
@@ -335,7 +340,7 @@ getLowest(){
         if [ $res -eq 2 ]
         then
             local tmp=`expr $3 + 1`
-            echo `getLowest "$i" "$res" $tmp`
+            echo `getLowest "$1" "$2" $tmp`
         else
         #Sinon on affiche le resultat
             if test $asc = "true"
@@ -352,7 +357,7 @@ getLowest(){
 }
 
 getLast(){
-    local res=`echo $1 | cut -d' ' -f1`
+    local res=`echo "$1" | cut -d' ' -f1`
     for i in $1
     do
         if [ `getLowest "$i" "$res" 0` = 1 ]
